#ifndef DEFINES_H
#define DEFINES_H

#include "types.h"

#define SETBIT(WORD,BIT)                    (WORD|=1<<BIT)
#define CLRBIT(WORD,BIT)                    (WORD&=~(1<<BIT))
#define CPLBIT(WORD,BIT)                    (WORD^=(1<<BIT))
#define WRITEBIT(WORD,BITPOS,BITLEVEL)      WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))
#define READBIT(WORD,BITPOS)                ((WORD>>BITPOS)&1)
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))
#define WRITENIBBLE(WORD,BITSTARTPOS,VALUE) WORD=((WORD&~(15<<BITSTARTPOS))|(VALUE<<BITSTARTPOS))
#define READNIBBLE(WORD,BITSTARTPOS)        ((WORD>>BITSTARTPOS)&15)
#define WRITEBYTE(WORD,BITSTARTPOS,BYTE)    WORD=((WORD&~((u32)255<<BITSTARTPOS))|((u32)BYTE<<BITSTARTPOS))
#define READBYTE(WORD,BITSTARTPOS)          ((WORD>>BITSTARTPOS)&255)
#define WRITENBITS(WORD,BITSTARTPOS,NBITS,VAL) WORD=((WORD&~(((1<<NBITS)-1)<<BITSTARTPOS))|(VAL<<BITSTARTPOS))

#endif // DEFINES_H
